### ISSUE TITLE
Some tests failed

### ISSUE THREAD

**Issue by johnnynanjiang** [LIT-Protocol/js-serverless-function-test#9]
Hi @glitch003 , some tests failed, one failure in here

1. got error when running `yarn run helloBLS`
> TypeError: LitActions.signBls is not a function

https://github.com/LIT-Protocol/js-serverless-function-test/blob/e2114e34d7d173ff1285e3ec165fa7511b4a69c6/js-sdkTests/helloworldBLS.js#L9

---

2. got error when running `yarn run sign`

```
[Lit-JS-SDK v2.2.11] 🔥 lit is ready. "litNodeClient" variable is ready to use globally.
/Users/nanjiang/Documents/dev/projects/Startup/J-Labs/projects/MPC/code/lit-protocol-js-serverless-function-test/node_modules/@lit-protocol/uint8arrays/src/lib/uint8arrays.js:15
        let charCode = str.charCodeAt(i);
                           ^

TypeError: str.charCodeAt is not a function
    at utf8Encode (/Users/nanjiang/Documents/dev/projects/Startup/J-Labs/projects/MPC/code/lit-protocol-js-serverless-function-test/node_modules/@lit-protocol/uint8arrays/src/lib/uint8arrays.js:15:28)
    at uint8arrayFromString (/Users/nanjiang/Documents/dev/projects/Startup/J-Labs/projects/MPC/code/lit-protocol-js-serverless-function-test/node_modules/@lit-protocol/uint8arrays/src/lib/uint8arrays.js:104:20)
    at LitNodeClientNodeJs.getLitActionRequestBody (/Users/nanjiang/Documents/dev/projects/Startup/J-Labs/projects/MPC/code/lit-protocol-js-serverless-function-test/node_modules/@lit-protocol/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.js:96:76)
    at LitNodeClientNodeJs.executeJs (/Users/nanjiang/Documents/dev/projects/Startup/J-Labs/projects/MPC/code/lit-protocol-js-serverless-function-test/node_modules/@lit-protocol/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.js:1088:38)
    at go (file:///Users/nanjiang/Documents/dev/projects/Startup/J-Labs/projects/MPC/code/lit-protocol-js-serverless-function-test/js-sdkTests/signTxn.js:34:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by Adarsh-Kumar28** [comment]
@johnnynanjiang 
1. The `signBls` function is no longer supported

**Comment by johnnynanjiang** [comment]
> @johnnynanjiang
> 
> 1. The `signBls` function is no longer supported

Thanks @Adarsh-Kumar28 for clarifying.

Just wonder does that mean only ECDSA is supported, and BLS won't be supported anymore, or it is just for the moment.
